server:
  port: 5050
spring:
  application:
    name: springboot-rabbit
    #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zhanglong
    password: zl123456
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
